export const MESHBLU_HOST       = 'meshblu.octoblu.dev'
export const OAUTH_CLIENT_ID    = '209b5b74-24a9-4ca0-acc1-7d9a0b7d539c'
export const OAUTH_PROVIDER_URI = 'https://oauth.octoblu.dev'
export const OCTOBLU_URL        = 'https://app.octoblu.dev'
export const OCTOBLU_API_URL    = 'https://api.octoblu.dev'
export const FLOWS_URL          = 'https://flows.octoblu.dev'
